{% set name = "flake8-pyi" %}
{% set version = "26.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6e846efa7bdf4221cbf35c5123b8e8882ab1220578e89db2294a077368ac4885

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - flake8 >=6,<8
    - pyflakes >=2.1.1

test:
  requires:
    - pip
    - python {{ python_min }}.*
  commands:
    - pip check
  imports:
    - flake8_pyi

about:
  home: https://github.com/ambv/flake8-pyi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A plugin for flake8 to enable linting .pyi files.

extra:
  recipe-maintainers:
    - xhochy
