{% set name = "flake8-pyi" %}
{% set version = "22.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 52152ae25efbd6329c6426a3b29a9073a696ba744502fb3e48581a47426ad4c8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - attrs
    - flake8 >=3.2.1
    - pyflakes >=2.1.1

test:
  imports:
    - pyi

about:
  home: https://github.com/ambv/flake8-pyi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A plugin for flake8 to enable linting .pyi files.

extra:
  recipe-maintainers:
    - xhochy
