{% set name = "flake8-pyi" %}
{% set version = "23.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bbd77cc87ecf3f042992e9097a72d1b7b4468cf6155dc4096c0880c07908b8d2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    # - python >=3.7
    - python
    - pip
    - hatchling
  run:
    - python
    - flake8 >=3.2.1,<7
    - ast-decompiler >=0.7.0,<1.0  # [py<39]
    - pyflakes >=2.1.1

test:
  imports:
    - pyi

about:
  home: https://github.com/ambv/flake8-pyi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A plugin for flake8 to enable linting .pyi files.

extra:
  recipe-maintainers:
    - xhochy
