{% set name = "flake8-pyi" %}
{% set version = "24.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2d4e55a499b160a9eeb696ca42d693f340fc0cc4a028e0fc9e3aaf3987cb51a1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    # - python >=3.8
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - flake8 >=6,<7
    - ast-decompiler >=0.7.0,<1.0  # [py<39]
    - pyflakes >=2.1.1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pyi

about:
  home: https://github.com/ambv/flake8-pyi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A plugin for flake8 to enable linting .pyi files.

extra:
  recipe-maintainers:
    - xhochy
